### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by pgajeshwar-coupa** [facebook/WebDriverAgent#585]
Hi,

I am trying to build WebDriverAgent.xcodeproj for appium. But whenever I am trying to build 'WebDriverAgentRunner' target it is failing with **ld: symbol(s) not found for architecture x86_64** error. I am not getting which files are not linked. Can someone please help me identify root cause of this issue.

I am using Xcode Version 8.2.1 (8C1002)

Thanks.

**Comment by marekcirkos** [comment]
Can you paste some logs, or say which symbols are missing. What Xcode version are you using?

**Comment by pgajeshwar-coupa** [comment]
Hi @marekcirkos,

xcode log:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_XCTRunnerDaemonSession", referenced from:
      objc-class-ref in XCUIElement+FBTap-7EA65A696964DABE.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am using Xcode Version 8.2.1 (8C1002)

**Comment by marekcirkos** [comment]
@pgajeshwar-coupa can you try Xcode 8.3.2?

**Comment by marekcirkos** [comment]
ping @pgajeshwar-coupa

**Comment by PavithraNavaneeth** [comment]
Hi @pgajeshwar-coupa , Any update on this issue ? Did you got it resolved. I am facing the similar issue with WebDriverAgent project on Xcode 8.2 (8C38)/MAC OS 10.11.6

Have you tried with Xcode 8.3 - is it working ? or did you got it resolved with xcode 8.2 ?

For xcode 8.3 - I have to update to Sierra OS. Kindly confirm.

Thanks,
Pavithra

**Comment by PavithraNavaneeth** [comment]
This issue got resolved after updating to latest MAC os/xcode to 8.3.2

**Comment by sixleaves** [comment]
i have the error on 8.3.2. only shit, i have both xcode8.3.3 and 8.2 are have this error!!!

**Comment by zhangkun0625** [comment]
i just have this error on xcode 8.2.1,hao can i solved it ?
